# Generated by Django 6.0.1 on 2026-02-10 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(db_column='tenant_uuid', on_delete=django.db.models.deletion.CASCADE, to='kyc.tenant', to_field='uuid')),
            ],
            options={
                'db_table': 'customers',
                'unique_together': {('tenant', 'external_ref')},
            },
        ),
        migrations.CreateModel(
            name='VerificationSession',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('current_step', models.IntegerField(default=1)),
                ('front_image', models.CharField(blank=True, max_length=255, null=True)),
                ('back_image', models.CharField(blank=True, max_length=255, null=True)),
                ('selfie_image', models.CharField(blank=True, max_length=255, null=True)),
                ('liveness_running', models.BooleanField(default=False)),
                ('liveness_completed', models.BooleanField(default=False)),
                ('liveness_verified', models.BooleanField(default=False)),
                ('liveness_confidence', models.FloatField(default=0)),
                ('liveness_challenges', models.JSONField(blank=True, null=True)),
                ('liveness_completed_count', models.IntegerField(blank=True, null=True)),
                ('liveness_total_count', models.IntegerField(blank=True, null=True)),
                ('verify_verified', models.BooleanField(default=False)),
                ('verify_confidence', models.FloatField(default=0)),
                ('verify_similarity', models.FloatField(default=0)),
                ('review_status', models.CharField(default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyc.customer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kyc.tenant')),
            ],
            options={
                'db_table': 'kyc_sessions',
            },
        ),
    ]
