# Generated by Django 6.0.1 on 2026-02-10 04:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.customer')),
                ('tenant', models.ForeignKey(db_column='tenant_uuid', on_delete=django.db.models.deletion.CASCADE, to='kyc.tenant', to_field='uuid')),
            ],
            options={
                'db_table': 'kyc_verification_links',
            },
        ),
    ]
