# Generated by Django 6.0.1 on 2026-02-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_verificationlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='citizenship_type',
            field=models.CharField(blank=True, choices=[('japanese', 'Japanese'), ('foreign', 'Foreign')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name_kana',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='prefecture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='document_back_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='document_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='document_front_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='residence_card_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='residence_card_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='residence_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='selfie_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='verification_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
