# Generated by Django 6.0.1 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0004_tenant_deleted_at_tenant_deleted_by_tenant_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationsession",
            name="detected_card_type",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="verificationsession",
            name="depth_variation_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="verificationsession",
            name="edge_consistency_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="verificationsession",
            name="physical_card_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="verificationsession",
            name="physical_card_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="verificationsession",
            name="tilt_analysis",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verificationsession",
            name="tilt_frames",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
